#!/bin/sh

for tf in tf1 tf2; do
  echo "== $tf"
  vdir=`mktemp -d /tmp/test-nvidia.XXXXXX`

  # Need Python 3.7 here as TF1 does not support 3.8
  virtualenv -q -p /usr/bin/python3.7 $vdir >/dev/null
  . $vdir/bin/activate

  pip install -q -r assets/requirements-$tf.txt
  python3 test-nvidia

  deactivate
  rm --preserve-root -rf $vdir
done
