#!/bin/sh
set -e

for tf in tf1 tf2; do
  #  Note: CUDA 11.0 only with CUDNN 8
  for BASE_IMAGE in \
    nvidia/cuda:10.0-cudnn7-runtime-ubuntu18.04 \
    nvidia/cuda:10.1-cudnn7-runtime-ubuntu18.04 \
    nvidia/cuda:10.2-cudnn7-runtime-ubuntu18.04 \
    nvidia/cuda:11.0-cudnn8-runtime-ubuntu18.04 \
  ; do
    echo "== $tf $BASE_IMAGE"
    work_dir=`dirname $0`
    image_id=`docker build -q --build-arg tf=$tf --build-arg BASE_IMAGE=$BASE_IMAGE -f assets/Dockerfile $work_dir`
    docker run --gpus all -it --rm -e TF_CPP_MIN_LOG_LEVEL=2 $image_id
    docker rmi $image_id >/dev/null || true
  done
done
