#!/bin/sh
set -e

# FIXME 1.15
for tensorflow_version in 2.4.3 2.5.1 2.6.0 2.12.\* 2.13.\* 2.14.\*; do

  BASE_IMAGE=invalid

  # These _probably_ match the tested build configurations at
  # https://www.tensorflow.org/install/source#linux
  case "$tensorflow_version" in
    1.15) BASE_IMAGE=nvidia/cuda:10.0-cudnn7-runtime-ubuntu18.04;;
    2.4.3) BASE_IMAGE=nvidia/cuda:11.0.3-cudnn8-runtime-ubuntu20.04;;
    2.5.*) BASE_IMAGE=nvidia/cuda:11.2.2-cudnn8-runtime-ubuntu20.04;;
    2.6.*) BASE_IMAGE=nvidia/cuda:11.2.2-cudnn8-runtime-ubuntu20.04;;
    2.7.*) BASE_IMAGE=nvidia/cuda:11.2.2-cudnn8-runtime-ubuntu20.04;;
    2.8.*) BASE_IMAGE=nvidia/cuda:11.2.2-cudnn8-runtime-ubuntu20.04;;
    2.9.*) BASE_IMAGE=nvidia/cuda:11.2.2-cudnn8-runtime-ubuntu20.04;;
    2.12.*) BASE_IMAGE=nvidia/cuda:12.3.2-cudnn9-runtime-ubuntu22.04;;
  esac

  # According to the docs at https://www.tensorflow.org/install/gpu, we should
  # use different package names depending on the major version of TF.
  if echo $tensorflow_version | grep -q ^1; then
    tensorflow_package=tensorflow-gpu
  else
     tensorflow_package=tensorflow
  fi

  echo "== $tensorflow_package $tensorflow_version $BASE_IMAGE"
  work_dir=`dirname $0`
  image_id=`docker build -q --build-arg tensorflow_package=$tensorflow_package --build-arg tensorflow_version=$tensorflow_version --build-arg BASE_IMAGE=$BASE_IMAGE -f assets/Dockerfile $work_dir`
  docker run --gpus all -it --rm -e TF_CPP_MIN_LOG_LEVEL=1 $image_id
  docker rmi $image_id >/dev/null || true
done
